### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by duwwtop** [edgelogs/Lighthouse-Monitor#1]
能给个部署教程吗

**Comment by hokyouni** [comment]
周六有时间的话写一下。其实就是填好所需要的值后，设置个定时任务。2022年3月25日 01:22，duwwtop ***@***.***>写道：

能给个部署教程吗

**Comment by duwwtop** [comment]
主要是怎么部署。。或者能写个部署到宝塔的教程

**Comment by hokyouni** [comment]
下载[Lighthouse-Monitor.py](https://github.com/edgelogs/Lighthouse-Monitor/blob/main/Lighthouse-Monitor.py)，记住文件路径，以下以`/root/Lighthouse-Monitor.py`为例。

根据[README.md](https://github.com/edgelogs/Lighthouse-Monitor#readme)的指导填好各种KEY。

宝塔面板-计划任务如图：
![image](https://user-images.githubusercontent.com/61335738/160232537-2b33a123-146d-4579-a5cc-75a74ef0a573.png)

可以在SSH执行一次`python3 /root/Lighthouse-Monitor.py`以测试是否正确部署。
